version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/insight_engine:/app/src/insight_engine
    environment:
      - REDIS_HOST=redis
      - API_KEY=test-key # For local development only
    depends_on:
      - redis
      - qdrant

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  qdrant:
    image: "qdrant/qdrant:latest"
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  worker:
    build: .
    command: "arq src.insight_engine.worker.WorkerSettings"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis