poll_interval_seconds: 15
cooldown_seconds: 60
adaptation_rules:
  - name: "High Inference Latency"
    query: "rate(http_requests_latency_seconds_sum[1m]) / rate(http_requests_latency_seconds_count[1m])"
    operator: ">"
    threshold: 0.5
    level: "DEGRADED"
  - name: "Critical Inference Latency"
    query: "rate(http_requests_latency_seconds_sum[1m]) / rate(http_requests_latency_seconds_count[1m])"
    operator: ">"
    threshold: 1.0
    level: "CRITICAL"
  - name: "High Error Rate"
    query: 'sum(rate(http_requests_total{status_code=~"5.."}[1m])) / sum(rate(http_requests_total[1m])) > 0.1'
    operator: ">"
    threshold: 0 # Query returns 1 if condition is true
    level: "CRITICAL"
