name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Run tests
        run: python -m pytest

      # - name: Run linter
      #   run: |
      #     # This step is a placeholder for a future sprint.
      #     # pip install ruff
      #     # ruff check .
