version: "3.8"

secrets:
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

networks:
  monitoring:

services:
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./observability/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki-config.yml:/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    volumes:
      - /var/log:/var/.log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./observability/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-search.enabled=true", "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo-config.yml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER_FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_admin_password
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped
    secrets:
      - grafana_admin_user
      - grafana_admin_password

volumes:
  prometheus_data: {}
  grafana_data: {}
