version: "3.7"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ./n8n/data:/home/node/.n8n
    # Wait for database to be ready, if using one.
    # command: /bin/sh -c "sleep 5; n8n start"
