services:
  fastapi:
    command:
      - "uvicorn"
      - "video_ai_system.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--reload"
    volumes:
      - ./src:/app/src
