version: "3.7"

secrets:
  n8n_secure_cookie:
    file: ./secrets/n8n_secure_cookie.txt

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - D:\video-ai-system-data\n8n:/home/node/.n8n
      - D:\video-ai-system-data\videos:/data
    environment:
      - N8N_SECURE_COOKIE_FILE=/run/secrets/n8n_secure_cookie
    secrets:
      - n8n_secure_cookie

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - D:\video-ai-system-data\videos:/data
      - D:\video-ai-system-data\models:/app/models
    depends_on:
      - n8n
      - qdrant

volumes:
  qdrant_data:
