name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo pip install docker-compose

      - name: Build the Docker image
        run: docker-compose -f video-ai-system/docker-compose.yml build fastapi
